// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEpU170NB1MHu_g-i03i4EM1HRxupyc0',
    appId: '1:21700152869:web:0e20fe76158ce81bc4f9cc',
    messagingSenderId: '21700152869',
    projectId: 'ayna-ff521',
    authDomain: 'ayna-ff521.firebaseapp.com',
    storageBucket: 'ayna-ff521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM2XFcLKrdGoh8jUc88z1o0tlszDpjwBI',
    appId: '1:21700152869:android:42c9025bed8ee21cc4f9cc',
    messagingSenderId: '21700152869',
    projectId: 'ayna-ff521',
    storageBucket: 'ayna-ff521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwffDWvmy3-yaK898Ns2BMIaqz3J0c5kM',
    appId: '1:21700152869:ios:ba369de3865cd6f2c4f9cc',
    messagingSenderId: '21700152869',
    projectId: 'ayna-ff521',
    storageBucket: 'ayna-ff521.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwffDWvmy3-yaK898Ns2BMIaqz3J0c5kM',
    appId: '1:21700152869:ios:ba369de3865cd6f2c4f9cc',
    messagingSenderId: '21700152869',
    projectId: 'ayna-ff521',
    storageBucket: 'ayna-ff521.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJEpU170NB1MHu_g-i03i4EM1HRxupyc0',
    appId: '1:21700152869:web:c0e16515359a6c24c4f9cc',
    messagingSenderId: '21700152869',
    projectId: 'ayna-ff521',
    authDomain: 'ayna-ff521.firebaseapp.com',
    storageBucket: 'ayna-ff521.appspot.com',
  );
}
